default_context:
    author_name: "bioio-devs"
    author_email: "brian.whitney@alleninstitute.org"
    hosting_github_username_or_org: "bioio-devs"
    project_name: "bioio-czi"
    project_slug: "bioio-czi"
    python_slug: "bioio_czi"
    project_short_description: "A Bioio reader plugin for reading czi images."
    hosting_pypi_username: "bioio-devs"
    license: "MIT License"